The data used to train a storytelling classifier and annotate the argument data is provided as part of:

Neele Falk and Gabriella Lapesa. 2022. Reports of personal experiences and stories in argumentation: datasets and analysis. In *Proceedings of the 60th Annual Meeting
of the Association for Computational Linguistics (Volume 1: Long Papers)*, pages 5530-5553, Dublin, Ireland. Association for Computational Linguistics.

and obtained from https://github.com/Blubberli/storytestimony/blob/main/datasets/whole_datasets.zip

In [1]:
import pandas as pd

In [4]:
cmv_raw = pd.read_csv("cmv_all_features.csv", sep="\t")
cmv_raw.head()

,id,post_text,label,postlength,past_tense,personal_pronouns,adverbs,auxliliary,subordinate_conj,named_entities,...,LD_Mean_Accuracy,WN_Mean_Accuracy,lsa_average_top_three_cosine,content_poly,hyper_verb_noun_Sav_Pav,flesch,gunningFog,chars_per_word,syllables_per_word,long_words
0,104,I think that Obama hasn't made any good decisi...,1,144,0.048611,0.083333,0.027778,0.020833,0.041667,0.041667,...,0.964043,0.992076,0.172414,10.153664,3.893164,34.9442,17.2473,5.3483,1.8308,0.2863
1,104,You may find this site to be interesting: Also...,1,645,0.023256,0.040310,0.079070,0.010853,0.026357,0.023256,...,0.964085,0.996761,0.122333,11.368421,3.103005,50.3458,15.0065,4.8708,1.6262,0.2445
2,104,"It's kind of hard to get an unbiased ""good"", a...",1,436,0.038991,0.011468,0.034404,0.006881,0.011468,0.059633,...,0.958166,0.992544,0.146184,10.800000,4.637055,79.6746,11.5970,4.1902,1.2730,0.1304
3,103,I don't believe that the military should have ...,0,148,0.013514,0.006757,0.033784,0.047297,0.027027,0.040541,...,0.953794,0.992799,0.143950,10.282132,4.878602,94.2292,9.3861,3.9794,1.1856,0.1468
4,103,"As we all know, military jobs often require no...",0,130,0.023077,0.007692,0.069231,0.007692,0.023077,0.000000,...,0.963719,0.991653,0.135000,10.985915,3.841794,84.6900,12.3125,4.3050,1.2021,0.1362

In [5]:
europolis_raw = pd.read_csv("europolis_all_features.csv", sep="\t")
europolis_raw.head()

,post_text,label,original_language,postlength,past_tense,personal_pronouns,adverbs,auxliliary,subordinate_conj,named_entities,...,LD_Mean_Accuracy,WN_Mean_Accuracy,lsa_average_top_three_cosine,content_poly,hyper_verb_noun_Sav_Pav,flesch,gunningFog,chars_per_word,syllables_per_word,long_words
0,"As it comes to Holland, the asylum procedures ...",1,pl,176,0.039773,0.017045,0.068182,0.017045,0.005682,0.011364,...,0.969000,0.996000,0.100000,12.692308,3.309086,80.7906,12.1376,4.0323,1.2419,0.1528
1,1007 I can only confirm that the situation for...,1,pl,131,0.007634,0.038168,0.030534,0.015267,0.038168,0.053435,...,0.958660,0.991753,0.140250,8.886792,4.602279,89.2435,9.8000,4.1200,1.2400,0.1724
2,You have also mentioned work. Can asylum work ...,1,pl,69,0.014493,0.014493,0.057971,0.014493,0.043478,0.014493,...,0.963608,0.989494,0.159608,9.010638,3.392227,88.2603,12.7062,3.7441,1.0630,0.0993
3,"In Belgium, so to speak, the situation is diff...",1,pl,109,0.027523,0.000000,0.073394,0.000000,0.018349,0.018349,...,0.963429,0.994381,0.167895,9.518519,4.188145,75.3400,8.2000,4.7917,1.4583,0.2593
4,I believe that selective immigration is needed...,1,pl,65,0.046154,0.046154,0.061538,0.015385,0.030769,0.030769,...,0.975455,0.991364,0.178750,6.250000,5.259389,74.4388,11.3182,4.5455,1.4000,0.2063

In [6]:
regroom_raw = pd.read_csv("regroom_all_features.csv", sep="\t")
regroom_raw.head()

,post_text,postlength,pers_pronouns,past_tense,label,personal_pronouns,adverbs,auxliliary,subordinate_conj,named_entities,...,LD_Mean_Accuracy,WN_Mean_Accuracy,lsa_average_top_three_cosine,content_poly,hyper_verb_noun_Sav_Pav,flesch,gunningFog,chars_per_word,syllables_per_word,long_words
0,When an attorney is a 'Debt Collector' (as per...,161,0.01,0.031056,1,0.006211,0.049689,0.000000,0.031056,0.012422,...,0.974286,0.991429,0.155455,7.066667,4.062439,59.1275,13.0780,4.7561,1.5000,0.2111
1,I work at a private university and we do not s...,74,0.08,0.040541,1,0.081081,0.013514,0.013514,0.027027,0.027027,...,0.956034,0.994138,0.191786,10.628571,3.409636,65.9845,12.0568,4.5323,1.5161,0.1714
2,I received a bill from an attorneys office reg...,255,0.06,0.129412,1,0.058824,0.047059,0.000000,0.007843,0.011765,...,0.956570,0.989012,0.181481,11.087379,4.077899,67.8527,10.8177,4.7746,1.5211,0.1954
3,I do NOT owe any debt but have a COMMON FIRST ...,136,0.04,0.007353,1,0.044118,0.007353,0.000000,0.000000,0.066176,...,0.960952,0.987810,0.130732,8.164179,4.439467,74.4992,8.0046,4.7586,1.4483,0.1389
4,Allow the States and/or local courts administe...,60,0.03,0.066667,1,0.033333,0.033333,0.016667,0.016667,0.033333,...,0.960354,0.992212,0.139184,10.270270,4.473685,91.1250,11.1111,3.7611,1.1278,0.0842

In [10]:
cols = set(cmv_raw.columns)
cols.remove("post_text")
cols.remove("label")
cmv_only = cmv_raw.drop(columns=cols)
cmv_only.rename(columns={"post_text": "text"}, inplace=True)
cmv_only.to_csv("storytelling_cmv_only.csv", sep="\t", index=False)

In [12]:
cols = set(regroom_raw.columns)
cols.remove("post_text")
cols.remove("label")
regroom_only = regroom_raw.drop(columns=cols)
regroom_only.rename(columns={"post_text": "text"}, inplace=True)

In [13]:
cols = set(europolis_raw.columns)
cols.remove("post_text")
cols.remove("label")
europolis_only = europolis_raw.drop(columns=cols)
europolis_only.rename(columns={"post_text": "text"}, inplace=True)

In [20]:
mixed = pd.concat((cmv_only, regroom_only, europolis_only), axis=0)
mixed = mixed.sample(frac=1)
mixed.head()
mixed.to_csv("storytelling_mixed.csv", sep="\t", index=False)